### ISSUE TITLE
How to use mini-django with uwsgi or any wsgi server?

### ISSUE THREAD

**Issue by davidkwast** [readevalprint/mini-django#7]
I am used to deploy regular Django with wsgi.py that django provides.

Have you tried deploying mini-django with a wsgi server?

Maybe I will try again in the next days. If I succeed I will post here.

**Comment by readevalprint** [comment]
hey yes it should work, mostly set `wsgi --env DJANGO_SETTINGS_MODULE=mini_django` let me know how it works

**Comment by davidkwast** [comment]
Thanks. I tried something similar but it was in the middle of a docker deploy. Next time I will try with a cleaner environment. You can close this issue if you like.
