### ISSUE TITLE
Small changes to make it work with latest Django 3.1.1

### ISSUE THREAD

**Issue by ivanistheone** [readevalprint/mini-django#8]
I'm using a file similar to `mini_django.py` in production (via WSGI via gunicorn) and recently tested it with latest version of Django 3.1.1.

We can't pass `**locals()` to configure anymore since there is some new validation in Django 3: all settings must be ALL_CAPS.

Here is a screenshot of the changes I had to make for it to work:

<img width="695" alt="works with lates Django 3 1 1" src="https://user-images.githubusercontent.com/163966/94219978-06cfb500-feb6-11ea-8140-b7f2475fc7f4.png">

Note `SECRET_KEY` and `ROOT_URLCONF` must be defined in main file AND in the SETTINGS dict.

If any of this looks useful and Django 3 support sounds useful, I can open a PR.

**Comment by readevalprint** [comment]
Yes a PR with those changes would be great. I remember running into this
issue but forgot to update the repo. Thanks for noticing.

**Comment by readevalprint** [comment]
Thank you
